import Logo from "@/assets/logo.svg"
import UserIcon from "@/assets/1.svg"
import SearchIcon from "@/assets/2.svg"
import WishListIcon from "@/assets/3.svg"
import CartIcon from "@/assets/4.svg"
import ChevronRightIcon from "@/assets/8.svg"
import ImageDetailIcon from "@/assets/16.svg"
import ImageDescriptionA from "@/assets/19.svg"
import ImageDescriptionB from "@/assets/20.svg"
import Icon21 from "@/assets/21.svg"
import Icon22 from "@/assets/22.svg"
import Icon23 from "@/assets/23.svg"
import Icon24 from "@/assets/24.svg"
import IconEvaluate from "@/assets/Evaluate.svg"

export {Logo,UserIcon,SearchIcon,CartIcon,WishListIcon,ChevronRightIcon,ImageDetailIcon,ImageDescriptionA,ImageDescriptionB,Icon21,Icon22,Icon23,Icon24,IconEvaluate}